<a href="https://colab.research.google.com/github/JustynaGoc/machine-learning-bootcamp/blob/main/Supervised/Basic/3_feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ekstrakcja cech

## 1.Importowanie bibliotek

In [1]:
import pandas as pd
import numpy as np
import sklearn

## 2. Załadowanie danych

In [12]:
import yfinance as yf
# Pobranie danych dla Amazon
ticker = "AMZN"
df = yf.download(ticker, start="2025-01-01", end="2026-06-22")

# Wyświetlenie pierwszych wierszy
df.head()

/tmp/ipykernel_2428/1500645796.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2025-01-01", end="2026-06-22")
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
Date
2025-01-02  220.220001  225.149994  218.190002  222.029999  33956600
2025-01-03  224.190002  225.360001  221.619995  222.509995  27515600
2025-01-06  227.610001  228.839996  224.839996  226.779999  31849800
2025-01-07  222.110001  228.380005  221.460007  227.899994  28084200
2025-01-08  222.130005  223.520004  220.199997  223.190002  25033300

## 3. Utworzenie kopii danych

In [20]:
df_raw = df.copy()
df = df_raw[:5]
df

Price            Close        High         Low        Open    Volume
Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
Date
2025-01-02  220.220001  225.149994  218.190002  222.029999  33956600
2025-01-03  224.190002  225.360001  221.619995  222.509995  27515600
2025-01-06  227.610001  228.839996  224.839996  226.779999  31849800
2025-01-07  222.110001  228.380005  221.460007  227.899994  28084200
2025-01-08  222.130005  223.520004  220.199997  223.190002  25033300

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2025-01-02 to 2025-01-08
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AMZN)   5 non-null      float64
 1   (High, AMZN)    5 non-null      float64
 2   (Low, AMZN)     5 non-null      float64
 3   (Open, AMZN)    5 non-null      float64
 4   (Volume, AMZN)  5 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 240.0 bytes

In [26]:
df['Volume'] = df['Volume'].astype('float')

/tmp/ipykernel_2428/605211629.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Volume'] = df['Volume'].astype('float')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2025-01-02 to 2025-01-08
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AMZN)   5 non-null      float64
 1   (High, AMZN)    5 non-null      float64
 2   (Low, AMZN)     5 non-null      float64
 3   (Open, AMZN)    5 non-null      float64
 4   (Volume, AMZN)  5 non-null      float64
dtypes: float64(5)
memory usage: 240.0 bytes

## 4. Generowanie nowych zmiennych

In [27]:
df.index

DatetimeIndex(['2025-01-02', '2025-01-03', '2025-01-06', '2025-01-07',
               '2025-01-08'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [29]:
df['day'] = df.index.day
df['month'] = df.index.month
df['year'] = df.index.year

/tmp/ipykernel_2428/1264535185.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day'] = df.index.day
/tmp/ipykernel_2428/1264535185.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df.index.month
/tmp/ipykernel_2428/1264535185.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df.index.year

In [30]:
df

Price,Close,High,Low,Open,Volume,day,month,year
Ticker,AMZN,AMZN,AMZN,AMZN,AMZN,,,
Date,,,,,,,,
2025-01-02,220.220001,225.149994,218.190002,222.029999,33956600.0,2,1,2025
2025-01-03,224.190002,225.360001,221.619995,222.509995,27515600.0,3,1,2025
2025-01-06,227.610001,228.839996,224.839996,226.779999,31849800.0,6,1,2025
2025-01-07,222.110001,228.380005,221.460007,227.899994,28084200.0,7,1,2025
2025-01-08,222.130005,223.520004,220.199997,223.190002,25033300.0,8,1,2025

## 5. Dyskretyzacja zmiennych ciągłych

In [31]:
df = pd.DataFrame( data = {'height': [175., 178.5,185., 191., 184.5, 183., 168.]})

In [32]:
df

   height
0   175.0
1   178.5
2   185.0
3   191.0
4   184.5
5   183.0
6   168.0

In [33]:
df['height_cut'] = pd.cut(x = df['height'], bins = 3)
df

   height          height_cut
0   175.0  (167.977, 175.667]
1   178.5  (175.667, 183.333]
2   185.0    (183.333, 191.0]
3   191.0    (183.333, 191.0]
4   184.5    (183.333, 191.0]
5   183.0  (175.667, 183.333]
6   168.0  (167.977, 175.667]

In [34]:
df['height_cat'] = pd.cut(x = df['height'], bins = (160,175,180,195))
df

   height          height_cut  height_cat
0   175.0  (167.977, 175.667]  (160, 175]
1   178.5  (175.667, 183.333]  (175, 180]
2   185.0    (183.333, 191.0]  (180, 195]
3   191.0    (183.333, 191.0]  (180, 195]
4   184.5    (183.333, 191.0]  (180, 195]
5   183.0  (175.667, 183.333]  (180, 195]
6   168.0  (167.977, 175.667]  (160, 175]

In [35]:
df['height_cat'] = pd.cut(x = df['height'], bins = (160,175,180,195), labels = ['small', 'medium', 'high'])
df

   height          height_cut height_cat
0   175.0  (167.977, 175.667]      small
1   178.5  (175.667, 183.333]     medium
2   185.0    (183.333, 191.0]       high
3   191.0    (183.333, 191.0]       high
4   184.5    (183.333, 191.0]       high
5   183.0  (175.667, 183.333]       high
6   168.0  (167.977, 175.667]      small

In [38]:
pd.get_dummies(df['height_cat'], drop_first= True, dtype= 'int', prefix = 'heigh')

   heigh_medium  heigh_high
0             0           0
1             1           0
2             0           1
3             0           1
4             0           1
5             0           1
6             0           0

## Ekstrakcja cech

In [39]:
df = pd.DataFrame( data = {'lang': [['PL', 'ENG'], ['GER', 'ENG', 'PL', 'FRA'], ['RUS']]})
df

                  lang
0            [PL, ENG]
1  [GER, ENG, PL, FRA]
2                [RUS]

In [40]:
df['lang_number'] = df['lang'].apply(len)
df

                  lang  lang_number
0            [PL, ENG]            2
1  [GER, ENG, PL, FRA]            4
2                [RUS]            1

In [42]:
df['PL_FLAG']= df['lang'].apply( lambda x: 1 if 'PL' in x else 0)
df

                  lang  lang_number  PL_FLAG
0            [PL, ENG]            2        1
1  [GER, ENG, PL, FRA]            4        1
2                [RUS]            1        0

In [43]:
df = pd.DataFrame(data = {'website': ['wp.pl', 'onet.pl', 'google.com']})
df

      website
0       wp.pl
1     onet.pl
2  google.com

In [46]:
df.website.str.split('.', expand = True)

        0    1
0      wp   pl
1    onet   pl
2  google  com

In [48]:
new =df.website.str.split('.', expand = True)
df['portal'] = new[0]
df['extension'] = new[1]
df

      website  portal extension
0       wp.pl      wp        pl
1     onet.pl    onet        pl
2  google.com  google       com