<a href="https://colab.research.google.com/github/JustynaGoc/machine-learning-bootcamp/blob/main/Supervised/1_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Przygotowanie danych

##1. Import bibliotek

In [50]:
import pandas as pd
import numpy as np
import sklearn

In [51]:
sklearn.__version__

'1.6.1'

## 2. Wygenerowanie danych

In [52]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', '  female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data = data)
df_raw

  size  color    gender  price  weight bought
0   XL    red    female  199.0     500    yes
1    L  green      male   89.0     450     no
2    M   blue      male   99.0     300    yes
3    L  green    female  129.0     380     no
4    M    red    female   79.0     410    yes

## 3. Utworzenie kopii danych

In [53]:
df = df_raw.copy()

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   5 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  5 non-null      int64
 5   bought  5 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes

## 4. Zmiana typu danych

In [55]:
#zmiana typy danych object na kategoryczne - dobre praktyki

for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weight']  = df['weight'].astype('float')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64
 4   weight  5 non-null      float64
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 752.0 bytes

In [57]:
# automatyzacja
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   5 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  5 non-null      int64
 5   bought  5 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes

In [58]:
for col in  df.select_dtypes(include=['object']).columns.tolist():
  df[col] = df[col].astype('category')
for col in  df.select_dtypes(include=['int64']).columns.tolist():
  df[col] = df[col].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64
 4   weight  5 non-null      float64
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 752.0 bytes

In [59]:
df.describe().T
# domyślnie   zwraca  statystyki wylacznie danych numerycznych

        count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [60]:
df.describe(include = ['category']).T

       count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      3  female    2
bought     5      2     yes    3

## 5. LabelEncoder

In [61]:
df

  size  color    gender  price  weight bought
0   XL    red    female  199.0   500.0    yes
1    L  green      male   89.0   450.0     no
2    M   blue      male   99.0   300.0    yes
3    L  green    female  129.0   380.0     no
4    M    red    female   79.0   410.0    yes

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [63]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [64]:
le.classes_

array(['no', 'yes'], dtype=object)

In [65]:
df['bought'] = le.fit_transform(df['bought'])

In [66]:
df

  size  color    gender  price  weight  bought
0   XL    red    female  199.0   500.0       1
1    L  green      male   89.0   450.0       0
2    M   blue      male   99.0   300.0       1
3    L  green    female  129.0   380.0       0
4    M    red    female   79.0   410.0       1

In [67]:
le.inverse_transform(df['bought'])

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [68]:
df['bought'] = le.inverse_transform(df['bought'])

In [69]:
df

  size  color    gender  price  weight bought
0   XL    red    female  199.0   500.0    yes
1    L  green      male   89.0   450.0     no
2    M   blue      male   99.0   300.0    yes
3    L  green    female  129.0   380.0     no
4    M    red    female   79.0   410.0    yes

## 6. OneHotEncoder

In [70]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output = False, drop = 'first')
encoder.fit(df[['size']])

OneHotEncoder(drop='first', sparse_output=False)

In [71]:
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [72]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [73]:
df

  size  color    gender  price  weight bought
0   XL    red    female  199.0   500.0    yes
1    L  green      male   89.0   450.0     no
2    M   blue      male   99.0   300.0    yes
3    L  green    female  129.0   380.0     no
4    M    red    female   79.0   410.0    yes

In [74]:
df_add = pd.DataFrame(encoder.fit_transform(df[['size']]), columns = encoder.get_feature_names_out(['size']))
df_add

   size_M  size_XL
0     0.0      1.0
1     0.0      0.0
2     1.0      0.0
3     0.0      0.0
4     1.0      0.0

In [75]:
df2= pd.concat([df,df_add], axis = 1)
df2

  size  color    gender  price  weight bought  size_M  size_XL
0   XL    red    female  199.0   500.0    yes     0.0      1.0
1    L  green      male   89.0   450.0     no     0.0      0.0
2    M   blue      male   99.0   300.0    yes     1.0      0.0
3    L  green    female  129.0   380.0     no     0.0      0.0
4    M    red    female   79.0   410.0    yes     1.0      0.0

## 7. Pandas get_dummies()

In [76]:
pd.get_dummies(data= df)

,price,weight,size_L,size_M,size_XL,color_blue,color_green,color_red,gender_ female,gender_female,gender_male,bought_no,bought_yes
0,199.0,500.0,False,False,True,False,False,True,False,True,False,False,True
1,89.0,450.0,True,False,False,False,True,False,False,False,True,True,False
2,99.0,300.0,False,True,False,True,False,False,False,False,True,False,True
3,129.0,380.0,True,False,False,False,True,False,False,True,False,True,False
4,79.0,410.0,False,True,False,False,False,True,True,False,False,False,True

In [77]:
pd.get_dummies(data= df, drop_first = True, dtype = 'int')

,price,weight,size_M,size_XL,color_green,color_red,gender_female,gender_male,bought_yes
0,199.0,500.0,0,1,0,1,1,0,1
1,89.0,450.0,0,0,1,0,0,1,0
2,99.0,300.0,1,0,0,0,0,1,1
3,129.0,380.0,0,0,1,0,1,0,0
4,79.0,410.0,1,0,0,1,0,0,1

In [78]:
pd.get_dummies(data= df, drop_first = True, prefix= 'new', dtype = 'int')

,price,weight,new_M,new_XL,new_green,new_red,new_female,new_male,new_yes
0,199.0,500.0,0,1,0,1,1,0,1
1,89.0,450.0,0,0,1,0,0,1,0
2,99.0,300.0,1,0,0,0,0,1,1
3,129.0,380.0,0,0,1,0,1,0,0
4,79.0,410.0,1,0,0,1,0,0,1

In [79]:
pd.get_dummies(data= df, drop_first = True, prefix= 'new', prefix_sep= '-', dtype = 'int')

,price,weight,new-M,new-XL,new-green,new-red,new-female,new-male,new-yes
0,199.0,500.0,0,1,0,1,1,0,1
1,89.0,450.0,0,0,1,0,0,1,0
2,99.0,300.0,1,0,0,0,0,1,1
3,129.0,380.0,0,0,1,0,1,0,0
4,79.0,410.0,1,0,0,1,0,0,1

In [80]:
pd.get_dummies(data= df, drop_first = True, columns = ['size'], dtype = 'int')

   color    gender  price  weight bought  size_M  size_XL
0    red    female  199.0   500.0    yes       0        1
1  green      male   89.0   450.0     no       0        0
2   blue      male   99.0   300.0    yes       1        0
3  green    female  129.0   380.0     no       0        0
4    red    female   79.0   410.0    yes       1        0

## 8. Standaryzacja StandardScaler

std() - pandas nieobciążony
std() - numpy obciążony

In [81]:
print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}\n")
print(f"Odchylenie standardowe: {df['price'].std():.4f}\n")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0

Odchylenie standardowe: 48.4768

In [82]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [83]:
from sklearn.preprocessing import scale

In [84]:
scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [85]:
from sklearn.preprocessing import StandardScaler

In [86]:
scaler = StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [87]:
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

In [88]:
df

  size  color    gender     price    weight bought
0   XL    red    female  1.845062  1.366002    yes
1    L  green      male -0.691898  0.623610     no
2    M   blue      male -0.461266 -1.603567    yes
3    L  green    female  0.230633 -0.415740     no
4    M    red    female -0.922531  0.029696    yes

## 9. Przygowanie danych do modelu

In [89]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   5 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  5 non-null      int64
 5   bought  5 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes

In [90]:
for col in  df.select_dtypes(include=['object']).columns.tolist():
  df[col] = df[col].astype('category')
for col in  df.select_dtypes(include=['int64']).columns.tolist():
  df[col] = df[col].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64
 4   weight  5 non-null      float64
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 752.0 bytes

In [91]:
#  kodowanie zmiennej docelowej bought

In [92]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['bought'] =le.fit_transform(df['bought'])
df

  size  color    gender  price  weight  bought
0   XL    red    female  199.0   500.0       1
1    L  green      male   89.0   450.0       0
2    M   blue      male   99.0   300.0       1
3    L  green    female  129.0   380.0       0
4    M    red    female   79.0   410.0       1

In [93]:
#  zmienne numeryczne skalowanie

In [94]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[['price', 'weight']]=  scaler.fit_transform(df[['price', 'weight']])
df

  size  color    gender     price    weight  bought
0   XL    red    female  1.845062  1.366002       1
1    L  green      male -0.691898  0.623610       0
2    M   blue      male -0.461266 -1.603567       1
3    L  green    female  0.230633 -0.415740       0
4    M    red    female -0.922531  0.029696       1

In [95]:
#zmienne kategoryczne

In [96]:
Categorical = df.select_dtypes(include=['category']).columns.tolist()
Categorical

['size', 'color', 'gender']

In [97]:
df =pd.get_dummies(data = df, drop_first  = True, columns = Categorical, dtype = 'int')

In [98]:
df

,price,weight,bought,size_M,size_XL,color_green,color_red,gender_female,gender_male
0,1.845062,1.366002,1,0,1,0,1,1,0
1,-0.691898,0.623610,0,0,0,1,0,0,1
2,-0.461266,-1.603567,1,1,0,0,0,0,1
3,0.230633,-0.415740,0,0,0,1,0,1,0
4,-0.922531,0.029696,1,1,0,0,1,0,0